nodeLinker: node-modules

packageExtensions:
  eslint-plugin-vue@*:
    dependencies:
      vue-eslint-parser: '*'
  '@aws-amplify/backend-cli@*':
    dependencies:
      '@aws-sdk/types': '*'
  '@aws-amplify/ui-vue@*':
    dependencies:
      '@aws-amplify/core': '*'
